### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eminSerin** [eminSerin/NBS-Predict#1]
- [ ] User MANUAL

- [ ] Refactoring! (Apply rules written in the[ MATLAB Style Guidelines 2.0 ](https://www.mathworks.com/matlabcentral/fileexchange/46056-matlab-style-guidelines-2-0)).

- [ ] Implement Gaussian Process classifier. 

- [ ] Implement better way to control nuisance variable.
